# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a1bb2046bc9a237b4224126dfc1ae0e5a08898249e3f51146bac68ec52fab353e311168c7bfa502fde79625553cd59a84241c8b90ff501e1790164a9d0da97

test:
  secret_key_base: e464a9cf8347f2eb1b4f4d987bd9fe5c96235e38c8f66c2d4865fbfaaa2c7838f367439f1ab0dd5a0694a26bcb5824b793e7992d3eba186d618fa202b1aed1b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
